-- Scoping wizard, project-type step (spec 045): a broad, grouped catalog of project types the wizard
-- offers (each later maps to a default feature bundle). Leadership manages it; members read.
create table if not exists public.project_types (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  group_name text not null,
  description text,
  is_custom boolean not null default false,
  active boolean not null default true,
  sort integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists project_types_group on public.project_types(group_name, sort, name);

alter table public.project_types enable row level security;

drop policy if exists "members read project types" on public.project_types;
create policy "members read project types" on public.project_types
  for select using (coalesce((auth.jwt() -> 'app_metadata' ->> 'is_member')::boolean, false));

drop policy if exists "leadership writes project types" on public.project_types;
create policy "leadership writes project types" on public.project_types
  for all
  using (public.is_superadmin() or public.is_lead() or public.is_global_pm())
  with check (public.is_superadmin() or public.is_lead() or public.is_global_pm());

insert into public.project_types (slug, name, group_name, sort) values
('ecommerce-store','E-commerce store','Commerce & retail',0),
('marketplace','Marketplace (multi-vendor)','Commerce & retail',1),
('supermarket','Supermarket / grocery','Commerce & retail',2),
('pharmacy','Pharmacy / parapharmacy','Commerce & retail',3),
('fashion-store','Fashion / apparel store','Commerce & retail',4),
('electronics-store','Electronics store','Commerce & retail',5),
('subscription-box','Subscription box','Commerce & retail',6),
('classifieds','Classifieds / second-hand','Commerce & retail',7),
('b2b-wholesale','B2B wholesale portal','Commerce & retail',8),
('auction','Auction / bidding','Commerce & retail',9),
('restaurant','Restaurant ordering app','Food & beverage',20),
('food-delivery','Food delivery (multi-restaurant)','Food & beverage',21),
('cloud-kitchen','Cloud kitchen','Food & beverage',22),
('cafe-loyalty','Cafe / coffee loyalty','Food & beverage',23),
('catering','Catering / meal prep','Food & beverage',24),
('table-reservation','Table reservation','Food & beverage',25),
('qr-menu','QR menu / dine-in ordering','Food & beverage',26),
('vtc','VTC / ride-hailing','Mobility & logistics',40),
('taxi-dispatch','Taxi dispatch','Mobility & logistics',41),
('carpooling','Carpooling','Mobility & logistics',42),
('car-rental','Car rental','Mobility & logistics',43),
('micromobility','Scooter / bike sharing','Mobility & logistics',44),
('courier-delivery','Delivery / courier','Mobility & logistics',45),
('fleet-management','Fleet management','Mobility & logistics',46),
('freight','Freight / trucking','Mobility & logistics',47),
('parking','Parking finder / booking','Mobility & logistics',48),
('last-mile','Last-mile logistics','Mobility & logistics',49),
('home-services','Home services (plumber, cleaner…)','On-demand services',60),
('beauty-salon','Beauty / salon booking','On-demand services',61),
('laundry','Laundry / dry cleaning','On-demand services',62),
('handyman','Handyman marketplace','On-demand services',63),
('pet-services','Pet services','On-demand services',64),
('on-demand-generic','On-demand services (generic)','On-demand services',65),
('crm','CRM','Business & internal tools',80),
('erp','ERP','Business & internal tools',81),
('intranet','Intranet / employee portal','Business & internal tools',82),
('hr-hris','HR / HRIS','Business & internal tools',83),
('project-management','Project management','Business & internal tools',84),
('inventory','Inventory management','Business & internal tools',85),
('pos','POS (point of sale)','Business & internal tools',86),
('field-service','Field service management','Business & internal tools',87),
('dms','Document management','Business & internal tools',88),
('helpdesk','Helpdesk / ticketing','Business & internal tools',89),
('admin-backoffice','Admin / back-office','Business & internal tools',90),
('bi-dashboard','Analytics / BI dashboard','Business & internal tools',91),
('telemedicine','Telemedicine','Health & wellness',100),
('clinic-booking','Clinic / appointment booking','Health & wellness',101),
('fitness','Fitness / workout','Health & wellness',102),
('nutrition','Nutrition / diet','Health & wellness',103),
('mental-health','Mental health / meditation','Health & wellness',104),
('patient-portal','Patient portal / EHR','Health & wellness',105),
('elearning','E-learning / LMS','Education',120),
('courses-marketplace','Online courses marketplace','Education',121),
('tutoring','Tutoring platform','Education',122),
('school-management','School management','Education',123),
('quiz-exam','Quiz / exam app','Education',124),
('kids-learning','Kids learning','Education',125),
('wallet','Mobile wallet / payments','Finance & fintech',140),
('banking','Banking app','Finance & fintech',141),
('lending','Lending / loans','Finance & fintech',142),
('investment','Investment / trading','Finance & fintech',143),
('crypto','Crypto exchange / wallet','Finance & fintech',144),
('insurtech','Insurance (insurtech)','Finance & fintech',145),
('budgeting','Expense / budgeting','Finance & fintech',146),
('crowdfunding','Crowdfunding','Finance & fintech',147),
('invoicing','Invoicing / accounting','Finance & fintech',148),
('social-network','Social network','Social & community',160),
('dating','Dating app','Social & community',161),
('forum','Community / forum','Social & community',162),
('chat-app','Messaging / chat app','Social & community',163),
('live-streaming','Live streaming','Social & community',164),
('membership-community','Membership community','Social & community',165),
('video-streaming','Video streaming (OTT)','Media & content',180),
('music-audio','Music / audio streaming','Media & content',181),
('podcast','Podcast','Media & content',182),
('news-magazine','News / magazine','Media & content',183),
('blog-cms','Blog / publishing (CMS)','Media & content',184),
('photo-sharing','Photo sharing','Media & content',185),
('real-estate-listings','Real estate listings','Real estate & property',200),
('long-term-rental','Property rental (long-term)','Real estate & property',201),
('short-term-rental','Short-term rental (Airbnb-like)','Real estate & property',202),
('property-management','Property management','Real estate & property',203),
('coworking','Co-working booking','Real estate & property',204),
('hotel-booking','Hotel booking','Travel & hospitality',220),
('trip-planner','Travel agency / trip planner','Travel & hospitality',221),
('transport-booking','Flight / bus / train booking','Travel & hospitality',222),
('tours-activities','Tours / activities booking','Travel & hospitality',223),
('vacation-rental','Hostel / vacation rental','Travel & hospitality',224),
('event-management','Event management','Events & ticketing',240),
('ticketing','Ticketing / box office','Events & ticketing',241),
('conference-app','Conference app','Events & ticketing',242),
('wedding-planning','Wedding planning','Events & ticketing',243),
('job-board','Job board','Jobs & recruitment',260),
('freelance-marketplace','Freelance marketplace','Jobs & recruitment',261),
('recruitment-ats','Recruitment / ATS','Jobs & recruitment',262),
('staffing','Gig / staffing','Jobs & recruitment',263),
('nonprofit','Nonprofit / donation','Other & generic',280),
('govtech','Government / civic services','Other & generic',281),
('iot-smart-home','IoT / smart home','Other & generic',282),
('gaming','Gaming / leaderboard','Other & generic',283),
('loyalty-rewards','Loyalty / rewards','Other & generic',284),
('saas-dashboard','SaaS web app (generic)','Other & generic',285),
('booking-generic','Booking / appointment (generic)','Other & generic',286),
('directory','Directory / listings (generic)','Other & generic',287),
('landing-marketing','Landing / marketing site','Other & generic',288),
('portfolio','Portfolio / personal site','Other & generic',289)
on conflict (slug) do nothing;
